/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

import entities.Categorie;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import service.CategorieService;

/**
 *
 * @author aeztic
 */
public class CategorieForm extends javax.swing.JPanel {
    private CategorieService cs;
    private DefaultTableModel model;
    private TableRowSorter<DefaultTableModel> rowSorter;
    /**
     * Creates new form CategorieForm
     */
    public CategorieForm() {
        initComponents();
        cs = new CategorieService();
        model = (DefaultTableModel) CategorieListe.getModel();
        rowSorter = new TableRowSorter<>(model);
        CategorieListe.setRowSorter(rowSorter);
        load();
        CategorieListe.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                int id = selectRow(evt);
            }
        });
       
        searchTxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                search(searchTxt.getText());
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                search(searchTxt.getText());
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                search(searchTxt.getText());
            }

            private void search(String str) {
                if (str.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + str, 1, 2, 3));
                }
            }
        });   
    }

    
    private void refreshAdd(Categorie c) {
        model.addRow(new Object[]{
                c.getId(),
                c.getCode(),
                c.getLibelle()
        });
    }
    
    public void load(){
        for(Categorie c : cs.findAll()){
            model.addRow(new Object[]{
                c.getId(),
                c.getCode(),
                c.getLibelle()
            });
        }
    }

    private boolean validField(String txt){
        return txt != null && !txt.trim().isEmpty();
    }

    public void clearField(){
        codeTxt.setText("");
        libelleTxt.setText("");
    }
    
    private int selectRow(MouseEvent evt) {
        int viewRow = CategorieListe.rowAtPoint(evt.getPoint());
        if (viewRow >= 0) {
            int modelRow = CategorieListe.convertRowIndexToModel(viewRow);
            int id = (int) model.getValueAt(modelRow, 0);
            codeTxt.setText((String) model.getValueAt(modelRow, 1));
            libelleTxt.setText((String) model.getValueAt(modelRow, 2));
            return id;
        }
        return -1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        codeTxt = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        libelleTxt = new javax.swing.JTextPane();
        addBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        CategorieListe = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        searchTxt = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("Code :");

        jScrollPane1.setViewportView(codeTxt);

        jLabel2.setText("Libelle :");

        jScrollPane2.setViewportView(libelleTxt);

        addBtn.setBackground(new java.awt.Color(0, 153, 0));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Ajouter");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Modifier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        clearBtn.setBackground(new java.awt.Color(102, 102, 102));
        clearBtn.setForeground(new java.awt.Color(255, 255, 255));
        clearBtn.setText("Effacer les champs");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(clearBtn)
                .addGap(86, 86, 86)
                .addComponent(jButton2)
                .addGap(43, 43, 43))
        );

        CategorieListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Code", "Libelle"
            }
        ));
        jScrollPane3.setViewportView(CategorieListe);

        jScrollPane4.setViewportView(searchTxt);

        jLabel3.setText("Rechercher :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearField();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String code = codeTxt.getText();
        String libelle = libelleTxt.getText();
        boolean valid = true;

        if (!validField(code)) {
            codeTxt.setBackground(Color.PINK);
            valid = false;
        } else {
            codeTxt.setBackground(Color.WHITE);
        }
        if (!validField(libelle)) {
            libelleTxt.setBackground(Color.PINK);
            valid = false;
        } else {
            libelleTxt.setBackground(Color.WHITE);
        }
        if (!valid) {
            JOptionPane.showMessageDialog(this , "Veuillez saisir toutes les informations !!");
            return;
        }
        Categorie c = new Categorie(code , libelle );
        if(cs.create(c)){
            JOptionPane.showMessageDialog(this, "Catégorie ajoute avec succès !");
            clearField();
            refreshAdd(c);
            
            Container parent = this.getParent(); // Get the parent container
            if (parent != null) {
                parent.remove(this); // Remove current panel
                ChambreForm chambreForm = new ChambreForm();
                parent.add(chambreForm); // Add the new panel
                parent.revalidate(); // Refresh the layout
                parent.repaint();    // Repaint the container
            } else {
                System.err.println("Parent container is null. Cannot switch to ChambreForm.");
            }
            return;
            }
    }//GEN-LAST:event_addBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = CategorieListe.getSelectedRow();
        if (selectedRow >= 0) {
            int id = (int) model.getValueAt(selectedRow, 0);
            String code = codeTxt.getText();
            String libelle = libelleTxt.getText();
            boolean valid = true;

            if (!validField(code)) {
                codeTxt.setBackground(Color.PINK);
                valid = false;
            } else {
                codeTxt.setBackground(Color.WHITE);
            }
            if (!validField(libelle)) {
                libelleTxt.setBackground(Color.PINK);
                valid = false;
            } else {
                libelleTxt.setBackground(Color.WHITE);
            }
            
            if (!valid) {
                JOptionPane.showMessageDialog(this, "Veuillez saisir toutes les informations !!");
                return;
            }

            Categorie c = cs.findById(id);
            if (c != null) {
                c.setCode(code);
                c.setLibelle(libelle);
                if (cs.update(c)) {
                    JOptionPane.showMessageDialog(this, "Catégorie  modifiée avec succès !");
                    model.setValueAt(code, selectedRow, 1);
                    model.setValueAt(libelle, selectedRow, 2);
                    clearField();
                } else {
                    JOptionPane.showMessageDialog(this, "Erreur lors de la modification de la catégorie .");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Catégorie introuvable !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner la catégorie à modifier.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Container parent = this.getParent(); // Get the parent container
            if (parent != null) {
                parent.remove(this); // Remove current panel
                ChambreForm chambreForm = new ChambreForm();
                parent.add(chambreForm); // Add the new panel
                parent.revalidate(); // Refresh the layout
                parent.repaint();    // Repaint the container
            } else {
                System.err.println("Parent container is null. Cannot switch to ChambreForm.");
            }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CategorieListe;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextPane codeTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane libelleTxt;
    private javax.swing.JTextPane searchTxt;
    // End of variables declaration//GEN-END:variables
}
